Mohamed user cell pages
ucsb-cs156-m23/proj-gauchoride-m23-9am-2 pull request #22
Opened 2023-08-17 21:50 UTC by Mohamed-Elfouly

Closes #16 #17 #6 

As a user, you are able to change your phone number via the interface on the profile page. Shown below. Input is taken via a modal also shown below. Change is shown instantly without the need to refresh the page. 100% mutation tested.

<img width="1280" alt="image" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/114381138/764c646b-db7e-4f98-bb07-518022ef54ed">

<img width="1280" alt="image" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/114381138/0d43a391-5f58-40ed-820f-6cb0c7b0baaa">

2023-08-17 21:59 UTC, Mohamed-Elfouly commented
<img width="1226" alt="image" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/114381138/f47c3f45-8721-468d-95eb-8151c611e156">

2023-08-20 22:29 UTC, cjyu81 commented
good to merge

2023-08-21 17:11 UTC, cjyu81 approved these changes
Looks good. Approving

2023-08-22 02:49 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +    //striker enable all
```suggestion
    // Stryker restore all
```
This is the proper version of the comment that restores Stryker testing.

2023-08-22 02:50 UTC, pconrad commented on frontend/src/main/pages/ProfilePage.js
> +                onChange={onChangePhoneNumber} // Update phone number state
```suggestion
                onChange={onChangePhoneNumber}
```

I wonder whether the comment is adding any valuable information here, or is just clutter?

2023-08-22 02:51 UTC, pconrad commented on frontend/src/tests/pages/CellPhone.test.js
> +        //await waitFor(() => expect(screen.getByText("987-654-3210")).toBeInTheDocument());
We try not to commit commented out code into the main branch

```suggestion
```

2023-08-22 02:51 UTC, pconrad commented on frontend/src/tests/pages/CellPhone.test.js
> +        //"Required request parameter 'cellPhone' for method parameter type String is not present"
The purpose of this comment is unclear.  Can we remove it?
```suggestion
```

2023-08-22 02:52 UTC, pconrad commented on frontend/src/tests/pages/CellPhone.test.js
> +        //axiosMock.onPut("/api/userprofile/update-cellPhone?cellPhone=123-456-7890").reply(202);
```suggestion
```

Commented out code?

2023-08-22 02:53 UTC, pconrad requested changes
There's one correction, and a lot of commented out code to fix.

2023-08-22 02:53 UTC, pconrad commented on frontend/src/tests/pages/CellPhone.test.js
> +});
```suggestion
```

Please remove this huge section of commented out code.

2023-08-22 20:52 UTC, cjyu81 approved these changes
Looks good

2023-08-22 21:37 UTC, cjyu81 submitted a review, later dismissed
Looks good. Approved

2023-08-23 21:20 UTC, pconrad submitted a review, later dismissed
LGTM

2023-08-23 21:21 UTC, merged