Charlie shift crud create page
ucsb-cs156-m23/proj-gauchoride-m23-9am-2 pull request #40
Opened 2023-08-21 04:46 UTC by cjyu81

Create page for CRUD Driver Shift Table. Had hiccup with mutation earlier but this time it works.

2023-08-21 15:14 UTC, cjyu81 commented
I will push a fix for this. Dont review yet

2023-08-21 18:38 UTC, cjyu81 commented
Fixes pushed. Ready for review

2023-08-21 23:23 UTC, adityapatil834 submitted a review, later dismissed

2023-08-22 03:33 UTC, pconrad approved these changes
LGTM

2023-08-22 04:00 UTC, chriscerie requested changes

2023-08-22 06:01 UTC, cjyu81 commented on frontend/src/main/pages/Shift/ShiftCreatePage.js
> +  }
Moving it into the event handler causes the following error:
![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/39837939/997ffd05-5e7d-4407-9d8f-8180e68ce5d8)

The example code RestaurantCreatePage.js from last lab uses this format so I'm not sure how to proceed with your suggested changes.

2023-08-22 06:32 UTC, chriscerie commented on frontend/src/main/pages/Shift/ShiftCreatePage.js
> +  }
> The example code RestaurantCreatePage.js from last lab uses this format

I hope to see this change then. Logic driven primarily from user input should be in event handlers separate from effects and render logic.

As for your code, it doesn't make sense to return elements from event handlers. Navigate imperatively with `useNavigate`.

2023-08-22 18:09 UTC, pconrad commented on frontend/src/main/pages/Shift/ShiftCreatePage.js
> +  }
@chriscerie Raises some good points, but those probably need to be incorporated into our stack and our examples at an earlier stage in the course.  For now, we'll let this go in as is, and I'll take @chriscerie 's points under consideration for refactoring the examples for F23—and if that goes well, we might create issues to refactor the legacy apps along the same lines.

2023-08-22 18:10 UTC, pconrad commented on frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
> +        //expect(mockToast).toBeCalledWith(`New shift Created - id: ${shift.id} day: ${shift.day}`);
Oof.. commented out code.  This should be removed before we merge.

2023-08-22 18:10 UTC, pconrad requested changes
Found a line of commented out code that should be removed.

2023-08-22 18:11 UTC, pconrad commented on frontend/src/tests/pages/Shift/ShiftCreatePage.test.js
> +        //expect(mockToast).toBeCalledWith(`New shift Created - id: ${shift.id} day: ${shift.day}`);
```suggestion
```

2023-08-23 00:47 UTC, cjyu81 commented
Comment deleted. Ready for review

2023-08-24 16:04 UTC, pconrad approved these changes
LGTM!

2023-08-24 16:04 UTC, merged