Bill Xin set up Privacy Policy, excluding adding the html file#34 2nd issue
ucsb-cs156-m23/proj-gauchoride-m23-9am-2 pull request #49
Opened 2023-08-22 22:12 UTC by abcdefucsb

As a user
I can see a privacy policy
So that I know how my data will be used

closes https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/issues/34

![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/80431618/28a1a411-7904-4f27-9ad6-0e6958d30eaf)

![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/80431618/0e82b92d-ba12-4236-804f-17345ab49b45)

2023-08-22 23:05 UTC, andrewthaii approved these changes, later dismissed
Looks good. Approving.

2023-08-23 21:28 UTC, pconrad requested changes
This acceptance criterion from Issue #34  has not been met:

- [ ]  The <Footer> component has the text Privacy Policy somewhere suitable, with a link to /privacy

Please remove the "Privacy Policy" button from the Navbar (where it was never supposed to be in the first place), and instead, add a link in the Footer, which is where the customer wants it to be.

2023-08-24 03:45 UTC, abcdefucsb commented
"privacy policy" is moved to the footer. My initial comment for this pr has been updated

2023-08-24 16:09 UTC, pconrad commented on frontend/src/main/pages/PrivacyPolicy.js
> +            <a href="privacy.html">Go to Privacy Policy</a>
Put the contents of `privacy.html`, which you deleted, here.

2023-08-24 16:10 UTC, pconrad requested changes
Why was privacy.html deleted?  

What I would have expected was that you would put that content into the PrivacyPolicy.js file.

Make sure that when you run the application, and click on the privacy policy link in the footer, that what comes up is actually the privacy policy.

2023-08-24 23:09 UTC, abcdefucsb commented
Modified the project with Dr. Conrad. My initial comment has been updated.

2023-08-25 05:35 UTC, Mohamed-Elfouly approved these changes
LGTM

2023-08-27 00:00 UTC, pconrad approved these changes
LGTM

2023-08-27 00:00 UTC, merged