Mohamed chat messages front end compoments
ucsb-cs156-m23/proj-gauchoride-m23-9am-2 pull request #51
Opened 2023-08-23 01:56 UTC by Mohamed-Elfouly

2023-08-23 19:09 UTC, cjyu81 submitted a review, later dismissed
Tests pass, looks good. Approving.

2023-08-23 21:42 UTC, pconrad approved these changes
LGTM as a first step.

I suggest that in a later PR, if you haven't already, that you take these steps:
1. Create a MessageDTO (data transfer object) that includes both the message, and extra fields from user that you want to send (e.g. given name, family name, email). I can go over both approaches with you in class or over chat.
2. Add either the users email or given name/family name to the message along with the user id.  
2.

2023-08-23 21:52 UTC, Mohamed-Elfouly commented
> LGTM as a first step.
> 
> I suggest that in a later PR, if you haven't already, that you take these steps:
> 
> 1. Create a MessageDTO (data transfer object) that includes both the message, and extra fields from user that you want to send (e.g. given name, family name, email). I can go over both approaches with you in class or over chat.
> 2. Add either the users email or given name/family name to the message along with the user id.

I have not done that. I would greatly appreciate the help in class

2023-08-24 19:27 UTC, Mohamed-Elfouly commented
Although I think these files should change, I want to consult the professor or TAs

2023-08-24 19:28 UTC, Mohamed-Elfouly commented
Also the Resolve conflicts button is disabled for some reason

2023-08-24 22:27 UTC, andrewthaii submitted a review, later dismissed
LGTM

2023-08-25 03:08 UTC, pconrad commented on frontend/src/stories/components/ChatMessage/ChatDisplay.stories.js
> +//const Template = () => <HelpRequestCreatePage storybook={true} />;
```suggestion
```

2023-08-25 03:08 UTC, pconrad requested changes
One small change

2023-08-25 03:15 UTC, pconrad approved these changes
LGTM

2023-08-26 16:34 UTC, abcdefucsb approved these changes
This code has been reviewed by others. LGTM!

2023-08-27 00:01 UTC, pconrad approved these changes
LGTM

2023-08-27 00:01 UTC, merged