Mohamed chat messages front end create
ucsb-cs156-m23/proj-gauchoride-m23-9am-2 pull request #52
Opened 2023-08-23 17:29 UTC by Mohamed-Elfouly

2023-08-23 19:10 UTC, cjyu81 submitted a review, later dismissed
Tests pass, looks good. Approving.

2023-08-23 21:44 UTC, pconrad commented on frontend/src/stories/components/ChatMessage/ChatDisplay.stories.js
> +//const Template = () => <HelpRequestCreatePage storybook={true} />;
Please remove commented out code.
```suggestion
```

2023-08-23 21:45 UTC, pconrad commented on frontend/src/stories/components/ChatMessage/ChatPanel.stories.js
> +//const Template = () => <HelpRequestCreatePage storybook={true} />;
sigh.  You know what to do.
```suggestion
```

2023-08-23 21:45 UTC, pconrad requested changes
a couple of instances of commented out code. otherwise LGTM

2023-08-24 19:32 UTC, Mohamed-Elfouly commented
Can't Resolve conflicts (button greyed out)

2023-08-24 22:27 UTC, andrewthaii approved these changes
LGTM

2023-08-25 03:10 UTC, pconrad commented on frontend/src/main/components/ChatMessage/ChatMessageForm.js
> +
```suggestion
```

2023-08-25 09:24 UTC, closed without merging