Addi gauchoride1
ucsb-cs156-m23/proj-gauchoride-m23-9am-2 pull request #70
Opened 2023-08-24 22:08 UTC by adityapatil834

2023-08-25 05:22 UTC, Mohamed-Elfouly commented on frontend/src/tests/pages/DriverPage.test.js
> +    // more test cases if needed
You might want to remove this comment

2023-08-25 05:22 UTC, Mohamed-Elfouly submitted a review, later dismissed
LGTM, look at comment though

2023-08-25 05:23 UTC, Mohamed-Elfouly commented
Provide description. VERY vague

2023-08-25 06:46 UTC, cjyu81 approved these changes
Changes looks good. The webapp works on my local machine:
![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-2/assets/39837939/2bf86b00-4638-4782-abbe-5a1e9b7c60f0)
Currently, only users with the driver role can see the drivers page. This is consistent with the acceptance criteria but you probably want to clarify this in the Release Notes or PR description. I think one would normally assume the Admin role alone would be enough to access every page. Atleast, I was confused because I had to go give myself the driver role in the admin page before the Driver page appeared.
Also please add more description to you PR, especially since this PR is very large.

2023-08-25 14:23 UTC, chriscerie requested changes
@Mohamed-Elfouly @cjyu81 Approving a pr that isn't ready to be reviewed isn't good. If a pr still needs an important element like a description or meaningful title, don't be afraid to request changes without approving.

2023-08-25 14:23 UTC, chriscerie commented on frontend/src/App.js
> +// import DriversPage from "main/pages/Driver/DriversPage";
```suggestion
```

2023-08-25 14:23 UTC, chriscerie commented on frontend/src/main/components/Driver/DriverShiftsTable.js
> +
Define this outside the component to not ruin table's shallow equality optimizations.
```suggestion
const columns = [
    {
        Header: 'id',
        accessor: 'id', // accessor is the "key" in the data
    },
    {
        Header: 'Day',
        accessor: 'day',
    },
    {
        Header: 'Shift start',
        accessor: 'shiftStart',
    },
    {
        Header: 'Shift end',
        accessor: 'shiftEnd',
    },
    {
        Header: 'Backup driver',
        accessor: 'driverBackupID',
    }
];

export default function DriverShiftsTable({ drivershifts }) {
```

2023-08-25 14:23 UTC, chriscerie commented on frontend/src/tests/pages/DriverPage.test.js
> +    // more test cases if needed
Yes, this isn't needed.

2023-08-26 16:25 UTC, abcdefucsb approved these changes
This pr has been code review by others. LGTM!

2023-08-26 17:18 UTC, chriscerie requested changes
This still needs a meaningful title & description.

2023-08-27 00:07 UTC, pconrad commented
@adityapatil834 That's a completely unacceptable title, and it's been pointed out multiple times.  At this point, for you to not have already fixed it really sends a message.   I'll leave for you to work out what that message is, but I'll give you a clue: it isn't good.

2023-08-27 00:09 UTC, pconrad commented
@cjyu81 and @Mohamed-Elfouly ... the right thing to do here would have been to either (a) not approve the pull request until the title was fixed, or (b) fix the title yourself, then approve it.

Approving it with a title this bad does NO one on the team any favors.

2023-08-27 00:12 UTC, pconrad commented
Thanks for the new title. 

For reference: https://ucsb-cs156.github.io/topics/pull_requests.html#pr-titles

2023-08-27 02:20 UTC, Mohamed-Elfouly submitted a review, later dismissed
LGTM

2023-08-27 02:33 UTC, pconrad submitted a review, later dismissed
LGTM

2023-08-27 04:52 UTC, pconrad requested changes

2023-08-27 04:52 UTC, pconrad commented on frontend/src/tests/components/Nav/AppNavbar.test.js
> +    test("Driver page link should appear for a user that is not a driver", async () => {
```suggestion
    test("Driver page link should appear for a user that is a driver", async () => {
```

2023-08-27 23:02 UTC, pconrad commented on frontend/src/tests/pages/DriverPage.test.js
> +    // more test cases if needed
```suggestion
```

Please remove the comment.   Third time you've been asked.

2023-08-27 23:02 UTC, pconrad requested changes
Please remove the comment.

2023-08-27 23:04 UTC, pconrad approved these changes
LGTM

2023-08-27 23:26 UTC, merged